### ISSUE TITLE
Error while logging in

### ISSUE THREAD

**Issue by patrizok** [3bl3gamer/tg_history_dumper#20]
[ERROR] :
unexpected error: mtproto.TL_rpc_error{ErrorCode:400, ErrorMessage:"You are using an outdated app that is no longer supported. To access your messages, please update your app to the latest version. If you don’t know how to update your app, go to https://telegram.org/dl"}

**Comment by 3bl3gamer** [comment]
API Layer is updated to 158, this error should be fixed. Sorry for long delay.
