### ISSUE TITLE
HTTP preview is not working

### ISSUE THREAD

**Issue by tangor86** [3bl3gamer/tg_history_dumper#35]
hello,

I run http preview like this:
tg_history_dumper -config "C:\Users\XXXXXXXX\go\bin\tg_history_dumper.json" -preview-http 127.0.0.1:9000

Then i go to the host and I see as below which is correct:
![image](https://github.com/user-attachments/assets/9ecba236-4c10-4eae-858b-11da813ac38e)

But when i click to the specific chat (any) and got navigated:
http://127.0.0.1:9000/chats/2241725579

I have error like this:
![image](https://github.com/user-attachments/assets/64ddc263-72b4-40db-b5e4-6721c663e22d)

Is it a bug or i am doing something wrong?

P.S: I do have all necessary files created after the export in the "history" folder:
![image](https://github.com/user-attachments/assets/ed2a582a-5027-46db-bd57-0343afdd5636)

**Comment by tangor86** [comment]
This is my config file if needed:
```
{
    "app_id": 11111111111111,
    "app_hash": "xxxxxxxxxxxxxxx",
    "request_interval_ms": 1000,
    "session_file_path": "tg.session",
    "out_dir_path": "history",
    "history": [
        {"id": xxxx}
    ],
    "stories": "none",
    "media": [
        {"type": "channel"}
    ],
    "history_limit": {
       "20000": {"type": "channel"}
    },
    "dump_account": "off",
    "dump_contacts": "off",
    "dump_sessions": "off"
}
```

**Comment by 3bl3gamer** [comment]
Preview currently requires a `history/account` file with current user's info (controlled by `"dump_account"`). In general, it should not be required, but as a workaround you can run the dumper once with `-dump_account=write` to create this `account` file.

**Comment by tangor86** [comment]
huge thanks it works with "dump_account": "write" !
