### ISSUE TITLE
Pictures are not displayed in the Preview

### ISSUE THREAD

**Issue by tangor86** [3bl3gamer/tg_history_dumper#36]
When go to the chat preview, images are not displayed, I think there is an issue with image path encoding.
<img width="884" alt="image" src="https://github.com/user-attachments/assets/2084738b-bbad-4b93-80fe-53962c8f6811">

**Comment by 3bl3gamer** [comment]
That's strange. Actually, it should not convert `%5c` to `/` but convert back slashes (`\`) to `/` before writing the path to HTML template. I've tested it in Windows and it worked (you have also run the dumper on Windows, haven't you?).

I've pushed an update where `fpathSeparatorsToURL` is replaced by build-in `filepath.ToSlash`. But they both should do the same so there is a little chance this will help.

If the error is still here, can you please add a
```go
fmt.Println(relPath, filepath.ToSlash(relPath))
```
just after
```go
relPath, _ := filepath.Rel(s.saver.Dirpath, file.FPath)
```
then open chat preview and check the output? It should print original and converted paths like
```
files\12_name\34_Media.jpg files/12_name/34_Media.jpg
```

**Comment by tangor86** [comment]
I took a new version of the code, rebuilt and re-fetched all the chats... actually i have seen this file beeing downloaded in the logs:
![image](https://github.com/user-attachments/assets/f50fb5f1-af99-47d3-ac46-d12ce3f00dd2)

I also added these 2 lines as you suggested in preview.go
![image](https://github.com/user-attachments/assets/ae6511d9-e2da-462c-b24c-7f39123c443f)

But I didn't see any output neither in console nor in the browser (screens attached)
![image](https://github.com/user-attachments/assets/73fc698d-29de-4e60-8b81-4aabc2a65178)

so I wonder if this code ever reached :) or am i checking in the wrong place?

**Comment by 3bl3gamer** [comment]
`loadChatFiles()` is responsible for searching for previously saved files. If was not called, there would be no files in preview. But there are some (though with broken paths).

Are you 100%-sure you are building and running correct files in correct directory? Maybe there is `tg_history_dumper` and `tg_history_dumper.exe` for example?

**Comment by tangor86** [comment]
you are right... i started like tg_history_dumper XXX instead of
./tg_history_dumper XXX
so it was taking some old version which i installed earlier with "go install"
New version i installed with git clone because i don't know how to update with "go"

Anyway, the output is like:
files\2194400374_Артур Сила Ума\63_Media_photo.jpg files/2194400374_Артур Сила Ума/63_Media_photo.jpg

and the image is shown now!
